
// Further Images
const Greer = ['img/projects/merch/GreerMockupFRONT.png']
const TheLastDinnerParty = ['img/projects/merch/TheLastDinnerPartyMockupFRONT.png']
const GoldenKnight = ['img/projects/merch/CUTennisClubShirtMockupFront.png', 'img/projects/merch/CUTennisClubShirtMockupBack.png']
const BebasBubble = ['img/projects/branding/BebasBubble/BebasBubble1.png','img/projects/branding/BebasBubble/BebasBubble2.png','img/projects/branding/BebasBubble/BebasBubble3.png','img/projects/branding/BebasBubble/BebasBubble4.png','img/projects/branding/BebasBubble/BebasBubble5.png','img/projects/branding/BebasBubble/BebasBubble6.png','img/projects/branding/BebasBubble/BebasBubble7.png','img/projects/branding/BebasBubble/BebasBubble8.png','img/projects/branding/BebasBubble/BebasBubble9.png','img/projects/branding/BebasBubble/BebasBubbleColor1.png','img/projects/branding/BebasBubble/BebasBubbleColor2.png','img/projects/branding/BebasBubble/BebasBubbleFonts.png','img/projects/branding/BebasBubble/BebasBubbleMockup1.jpg','img/projects/branding/BebasBubble/BebasBubbleMockup2.jpg','img/projects/branding/BebasBubble/BebasBubbleMockup3.jpg']
const MoltenMetal = ['img/projects/branding/MoltenMetal/MoltenMetalWorksBranding_LogoSecondarywhite.png','img/projects/branding/MoltenMetal/MoltenMetalWorksBranding-06.png','img/projects/branding/MoltenMetal/MoltenMetalWorksBranding-07.png','img/projects/branding/MoltenMetal/MoltenMetalWorksBranding-09.png','img/projects/branding/MoltenMetal/MoltenMetalWorksBranding-10.png','img/projects/branding/MoltenMetal/MoltenMetalWorksBranding-11.png','img/projects/branding/MoltenMetal/MoltenMetalWorksFonts.png','img/projects/branding/MoltenMetal/MoltenMetalWebsite1.png','img/projects/branding/MoltenMetal/MoltenMetalWebsite2.png']
const VIPStructures = ['img/projects/branding/VIPStructures/2023SummerInternscopyLarge.jpeg','img/projects/branding/VIPStructures/BestCompaniesToWorkForNewYork2023.jpg','img/projects/branding/VIPStructures/June2023_WelcomingNewHires.jpg','img/projects/branding/VIPStructures/SpecificRecruitingPosts_7-24-23_Insta.jpg','img/projects/branding/VIPStructures/SpecificRecruitingPosts_7-24-23_Insta2.jpg','img/projects/branding/VIPStructures/WordCloudAdTemplate3.jpg']
// const CommunityBank = ['img/projects/branding/CommunityBank/CFSI Posters v10 blue-1.png','img/projects/branding/CommunityBank/Syracuse Crunch v6 Mockup.mp4','img/projects/branding/CommunityBank/CB_PA_Award&Logo_Banner_13.6x4_4c-1.png','img/projects/branding/CommunityBank/CB_SYR-GO_Digital-Invite_6x9_RGB.jpg','img/projects/branding/CommunityBank/CB_Congratulations_Leadership Awards_Wilkes Barre, PA_9.87x10_4c-1.png','img/projects/branding/CommunityBank/CB_Brand__Oneonta_7x4.5_4c-1.png','img/projects/branding/CommunityBank/CB_Brand_GVHR_Geneseo_3.5x5_4c-1.png','img/projects/branding/CommunityBank/CB_Brand_TheatreAdventure_5x5.625_4c-1.png','img/projects/branding/CommunityBank/BranchSign_432x216px_RGB v2-1.png','img/projects/branding/CommunityBank/UnitedWayNursesPantry_432x216px_RGB.png','img/projects/branding/CommunityBank/1024x588 v3.5 Final.mp4','img/projects/branding/CommunityBank/6x9_Overprint_BetterThanPrime_MOCKUPv2-1.png','img/projects/branding/CommunityBank/6x9_Overprint_CheckingReferral-MOCKUP-1.png']
const CommunityBank = ['img/projects/branding/CommunityBank/CFSI Posters v10 blue-1.png','img/projects/branding/CommunityBank/Syracuse Crunch v6 Mockup.mp4','img/projects/branding/CommunityBank/CB_PA_Award&Logo_Banner_13.6x4_4c-1.png','img/projects/branding/CommunityBank/CB_Congratulations_Leadership Awards_Wilkes Barre, PA_9.87x10_4c-1.png','img/projects/branding/CommunityBank/CB_Brand__Oneonta_7x4.5_4c-1.png','img/projects/branding/CommunityBank/CB_Brand_GVHR_Geneseo_3.5x5_4c-1.png','img/projects/branding/CommunityBank/CB_Brand_TheatreAdventure_5x5.625_4c-1.png','img/projects/branding/CommunityBank/BranchSign_432x216px_RGB v2-1.png','img/projects/branding/CommunityBank/UnitedWayNursesPantry_432x216px_RGB.png','img/projects/branding/CommunityBank/1024x588 v3.5 Final.mp4','img/projects/branding/CommunityBank/6x9_Overprint_BetterThanPrime_MOCKUPv2-1.png','img/projects/branding/CommunityBank/6x9_Overprint_CheckingReferral-MOCKUP-1.png']
const KissMyKloset = ['img/projects/branding/KissMyKloset/Kiss My Kloset Mockup 2.jpg','img/projects/branding/KissMyKloset/Kiss My Kloset Logo Condensed-Square-LowerM.png','img/projects/branding/KissMyKloset/Kiss My Kloset Logo Condensed-LowerM.png','img/projects/branding/KissMyKloset/Kiss My Kloset Logo Condensed-Square-UpperM.png','img/projects/branding/KissMyKloset/Kiss My Kloset Logo Condensed-UpperM.png','img/projects/branding/KissMyKloset/Kiss My Kloset Logo.png']
const Capstone = ['img/projects/merch/Capstone/HeroCapstoneImage.jpeg','img/projects/merch/Capstone/thosewhocareposterIRL copy2.jpeg','img/projects/merch/Capstone/ThoseWhoCarePosterN.jpeg','img/projects/merch/Capstone/ThoseWhoCareAlbumCover.jpeg','img/projects/merch/Capstone/ThoseWhoCareAlbumCover copy.jpeg','img/projects/merch/Capstone/ThoseWhoCareAlbumCoverBACK.jpeg','img/projects/merch/Capstone/IRLThoseWhoCareBusinessCard.jpg','img/projects/merch/Capstone/ThoseWhoCare_BusinessCard_front copy.jpeg','img/projects/merch/Capstone/SoundsOfDaylightIRLPoster.jpg','img/projects/merch/Capstone/SoundOfDaylightPoster.jpeg','img/projects/merch/Capstone/SoundsOfDaylightAlbumCover.jpeg','img/projects/merch/Capstone/moreSoundOfDaylightAlbumCovers copy.jpeg','img/projects/merch/Capstone/SoundOfDaylightAlbumCoverBACK copy.jpeg','img/projects/merch/Capstone/IRLSoundOfDaylightBusinessCard.jpg','img/projects/merch/Capstone/SoundOfDaylight_BusinessCard_front copy.jpeg','img/projects/merch/Capstone/RearviewIRLPoster.jpg','img/projects/merch/Capstone/Rearview_Poster.jpeg','img/projects/merch/Capstone/RearviewAlbumCover.jpeg','img/projects/merch/Capstone/Rearview_AlbumCover-73 copy.jpeg','img/projects/merch/Capstone/Rearview_AlbumCover-72 copy.jpeg','img/projects/merch/Capstone/IRLRearviewBusinessCard.jpg','img/projects/merch/Capstone/Rearview_BusinessCard_front copy.jpeg']
const MidnightKisses = ['img/projects/merch/MidnightKisses/Midnight Kisses Signature Closeup.jpg','img/projects/merch/MidnightKisses/Midnight Kisses No text.jpg']
const NorthBloom = ['img/projects/musicposters/NorthBloom ReallyTinyTour Poster v2 copy.jpg','img/projects/musicposters/NorthBloomReallyTinyTourPoster_TheTuaLingua.png']
const RussettPR = ['img/projects/branding/russettpr/Hardy PDF Portfolio-11 copy.png','img/projects/branding/russettpr/Hardy PDF Portfolio-12 copy.png','img/projects/branding/russettpr/Hardy PDF Portfolio-13 copy.png','img/projects/branding/russettpr/Hardy PDF Portfolio-14 copy.png','img/projects/branding/russettpr/Hardy PDF Portfolio-15 copy.png']
const BillieEilish = ['img/projects/merch/Billie Eilish Tee Yellow Text Blue Shirt.jpg','img/projects/merch/Billie Eilish Tee White Text Blue Shirt.jpg']
const JalenNgonda = ['img/projects/merch/JalenNgondaMockup_Closeup.jpg','img/projects/merch/JalenNgondaDesign_Closeup.jpg']
const GreerBigSmile = ['img/projects/merch/Greer Big Smile/Greer Big Smile Shirt Design.jpg','img/projects/merch/Greer Big Smile/Greer Big Smile Shirt copy.jpg']
const CapitolHillBlockParty = ['img/projects/merch/CHBP_shirt_FRONT.jpg']
const DanceWater = ['img/projects/branding/DanceWater/DanceWater Logo 1.jpg','img/projects/branding/DanceWater/DanceWater Logo 2.jpg','img/projects/branding/DanceWater/DanceWater Logo Splash.jpg','img/projects/branding/DanceWater/DanceWater Signature 1.jpg','img/projects/branding/DanceWater/DanceWater Signature 2.jpg']
// const  = ['']


// Projects
const posters = [
    {"file":'img/projects/musicposters/NorthBloom ReallyTinyTour Poster.jpg',"Description":'<p>A commisioned piece for singer/songwriter NorthBloom\'s "Really Tiny Tour"</p>',"title":'North Bloom',"imgs":NorthBloom},
    {"file":'img/projects/musicposters/365-Day150-April20.jpeg',"Description":'<p>A commisioned piece for the band The Kiwis\' live show at The Finish Line</p>',"title":'The Kiwis'},
    {"file":'img/projects/musicposters/365-Day15-Nov2Large.jpeg',"Description":'<p>A piece made through collage and mixed-media exploration, highlighting Dafna\'s new single "Want Me Bad</p>',"title":'Dafna'},
    {"file":'img/projects/musicposters/365-Day42-November29.png',"Description":'<p>A commisioned piece for The Kiwis\' new Album Release</p>',"title":'The Kiwis'},
    {"file":'img/projects/musicposters/365-Day232-March3.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments based on albums/songs I\'ve been listening to</p>',"title":'Magdalen Bay'},
    {"file":'img/projects/musicposters/365-Day163-May15.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments based on albums/songs I\'ve been listening to</p>',"title":'Jalen Ngonda'},
    {"file":'img/projects/musicposters/365-Day94-February6Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments based on albums/songs I\'ve been listening to</p>',"title":'Miniature Tigers'},
    {"file":'img/projects/musicposters/365-Day157-May1.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments based on albums/songs I\'ve been listening to</p>',"title":'Arctic Monkeys'},
    {"file":'img/projects/musicposters/365-Day209-August5-SS.jpg',"Description":'<p>A piece of typographic expression, collage, and design experimentation for Cage The Elephant\'s Neon Pill Tour show at SPAC</p>',"title":'Cage The Elephant'},
    {"file":'img/projects/musicposters/365-Day97-February16Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments based on albums/songs I\'ve been listening to</p>',"title":'Between Friends'},
    {"file":'img/projects/musicposters/365-Day93-February5Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments based on albums/songs I\'ve been listening to</p>',"title":'Rex Orange County'},
    {"file":'img/projects/musicposters/365-Day149-April19.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments based on albums/songs I\'ve been listening to</p>',"title":'Maggie Rogers'},
    ]

const merch = [
    {"file":'img/projects/merch/CHBP_shirt_BACK.jpg',"Description":'<p>An original tee desigend for Capitol Hill Block Party 2025.</p>',"title":'Capitol Hill Block Party',"imgs":CapitolHillBlockParty},
    {"file":'img/projects/merch/MidnightKisses/Midnight Kisses_showcase.png',"Description":'<p>A commisioned piece for singer/songwriter Amanda Chloe\'s new song "Midnight Kisses"</p>',"title":'Amanda Chloe',"imgs":MidnightKisses},
    {"file":'img/projects/merch/Greer Big Smile/Greer Big Smile Shirt png.png',"Description":'<p>A piece of original merchandise designed for Greer\'s new album "Big Smile"</p>',"title":'Greer \'Big Smile\'',"imgs":GreerBigSmile},
    {"file":'img/projects/merch/JalenNgondaMockup.png',"Description":'<p>A piece of original merchandise created for Jalen Ngonda\'s album \"Come Around and Love Me\"</p>',"title":'Jalen Ngonda',"imgs":JalenNgonda},
    {"file":'img/projects/merch/Capstone/capstonethumbnail.jpg',"Description":'<p>In my senior capstone project at Clarkson University, I crafted branding for a fictional record label and three bands.</p><p> I designed logos, business cards, posters, and album covers, before bringing these designs to life in physical form.</p>',"title":'Capstone Records',"imgs":Capstone},
    {"file":'img/projects/merch/GoldenKnightTennisLogo.png',"Description":'<p>Commisioned merchandise created for Clarkson University\'s Tennis Club</p>',"title":'Clarkson Golden Knights',"imgs":GoldenKnight},
    {"file":'img/projects/merch/GreerMockupBACK.png',"Description":'<p>A piece of original merchandise based on Greer\'s EP \"Happy People\"</p>',"title":'Happy People',"imgs":Greer},
    {"file":'img/projects/merch/TheLastDinnerPartyMockupCOLOR-FRONT.png',"Description":'<p>A piece of original merchandise based on The Last Dinner Party\'s album \"Prelude To Ecstasy\"</p>',"title":'The Last Dinner Party',"imgs":TheLastDinnerParty},
    {"file":'img/projects/merch/BillieEilishMockup.png',"Description":'<p>A piece of original merchandise based on Billie Eilish\'s album \"Hit Me Hard and Soft\"</p>',"title":'Billie Eilish',"imgs":BillieEilish},
]

const branding = [
    {"file":'img/projects/branding/CommunityBank/Thumbnail.jpg',"Description":'<p>A Selection of work from my time as a Marketing Associate at Community Bank NA</p><p>• Designed infographs, advertisements, and ohter media for internal and external use </p><p>• Created Motion Graphics for ATM Screens, advertisements shown during Syracuse Crunch hockey matches, and more </p><p>• Developed Community Bank\'s Financial Literacy lesson plans to teach individuals of any age the importance of money and banking</p>',"title":'Community Bank',"imgs":CommunityBank},
    {"file":'img/projects/branding/VIPStructures/Vipstructurescopy.jpg',"Description":'<p>A Selection of work from my time as a Marketing Associate at VIP Structures</p><p>• Created ads and social media posts for VIP Structures and associated companies </p><p>• Designed emails for internal use </p><p>• Updated and maintained multiple websites </p><p>• Researched general marketing trends in the industry and built the grounds for VIP’s future marketing plans</p>',"title":'VIP Structures',"imgs":VIPStructures},
    {"file":'img/projects/branding/MoltenMetal/MoltenMetalofNYThumbnail.jpg',"Description":'<p>Logo and Website developed for a client </p><p> Owned by Greg Myka, Molten Metal of NY handcrafts personalized one-of-a-kind artwork, using repurposed objects, and by cutting, shaping, and transforming metal and wood. This logo and branding was created to express this unique business.<p>',"title":'Molten Metal',"imgs":MoltenMetal},
    {"file":'img/projects/branding/russettpr/russettprchristmas.png',"Description":'<p>A Selection of work from my time as a Marketing Associate at Russett PR</p><p>Crafted social media posts, advertisements, and infographics for both Russett PR and its clients while working closely with the PR department to plan photo shoots and other events</p>',"title":'Russett PR',"imgs":RussettPR},
    {"file":'img/projects/branding/DanceWater/DanceWater Mockup.jpg',"Description":'<p>Wordmark developed for a client. </p><p> Dance Water is a beverage company that wanted to showcase the energy and positivity that goes into the world of dance.</p>',"title":'Dance Water',"imgs":DanceWater},
    {"file":'img/projects/branding/KissMyKloset/Kiss My Kloset Mockup.jpg',"Description":'<p>Logo and Branding developed for a client </p><p> Owned by Amy Jelks, Kiss My Kloset is a new and upcoming fashion brand.<p> <p>Amy approached me to design a logo that would encapsulate the bold, modern essence of her clothing brand. The goal was to create a visually striking and versatile identity that reflected the edgy, fashion-forward nature of the brand while resonating with its target audience.</p> <p>Drawing on my expertise in branding, I developed a sleek and sophisticated logo that combines contemporary aesthetics with a timeless appeal. This design not only embodies the brand\'s unique personality but also establishes a strong foundation for its visual identity.',"title":'Kiss My Kloset',"imgs":KissMyKloset},
    {"file":'img/projects/branding/BebasBubble/BebasBubbleThumbnail.png',"Description":'<p>Logo and Packaging for fictional hard seltzer brand, "Bebas Neue", developed as a conceptual project</p>',"title":'Bebas Bubble',"imgs":BebasBubble},
]

const otherProjects = [
    {"file":'img/projects/Other/365posters/365-Day216-October26.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day215-October9.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day201-July10.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day71-January14Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day221-December29.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day52-December9Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day230-February10.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day172-May24.png',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day198-July7.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day9-October27Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day156-April30.jpg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day147-April17.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day46-December3Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day53-December10Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
    {"file":'img/projects/Other/365posters/365-Day102-February21Large.jpeg',"Description":'<p>A piece from a collection of typographic expression, collage, and design experiments done daily for 365 days</p>',"title":''},
]

const projArray = [
    posters, merch, branding, otherProjects
]